### ISSUE TITLE
Is it all ok with Russia and Republic of Kazakhstan?

### ISSUE THREAD

**Issue by niktob560** [egyleader/flutter_country#1]
There is phone codes ``[+73XX, +74XX, +75XX, +78XX, +79XX]`` and ``[+76XX, +77XX]``  
Is it necessary to have the ``XX`` part in suffixes? There are no countries with such codes and I really have no idea how to use this

**Comment by egyleader** [comment]
thanks for your patience .. now you can use flutter_country `version  0.1.0` witch hase better data sets and perfomance ,,   and phonecodes are renamed to `callingCodes` witch give you a list of Strings without any special symbols like [ + or XX]
